#!/bin/bash
DIR=/var/www/ciudad
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/usr/local/lib/node_modules
NODE=/usr/local/bin/node

test -x $NODE || exit 0

function start_app {
  NODE_ENV=development nohup "$NODE" "$DIR/bin/www" 1>>"$DIR/logs/ciudad.log" 2>&1 &
  echo $! > "$DIR/pids/ciudad.pid"
}

function stop_app {
  kill `cat $DIR/pids/ciudad.pid`
}

case $1 in
   start)
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: ciudad {start|stop}" ;;
esac
exit 0
